name: 'Infra Visualiser Action'
description: 'Analyze Terraform/OpenTofu recipes, generate graphs, and upload to platform'
author: 'Smithy'

inputs:
  directory:
    description: 'Path (relative to repo root) to the Terraform/OpenTofu recipe'
    required: true
  recipe_nickname:
    description: 'Nickname for this recipe that you set on the platform'
    required: true
  host:
    description: 'Base URL of the platform host (used as OIDC audience and upload target)'
    required: false
    default: 'https://grafos.ai'
  gcp_credentials_json:
    description: 'GCP service account JSON credentials for authenticating with Google Cloud Provider'
    required: false
  use_terraform:
    description: 'Use Terraform instead of OpenTofu for init and plan commands'
    required: false
    default: 'false'
  upload_to_github:
    description: 'Upload the generated archive as a GitHub Artifact and notify the server'
    required: false
    default: 'false'
  github_token:
    description: 'GitHub Token (required if upload_to_github is true)'
    required: false
  include_markdown:
    description: 'Also add markdown (*.md) files from the root of the repository to the archive'
    required: false
    default: 'false'

runs:
  using: 'docker'
  image: 'Dockerfile'

permissions:
  id-token: write
  contents: read
  # Needed to list artifacts in the GitHub Actions API
  # used when the uploade to github is enabled
  actions: read

branding:
  icon: 'box'
  color: 'blue'
