name: 'Infra Visualiser Action'
description: 'Analyze Terraform/OpenTofu recipes, generate graphs, and upload to platform'
author: 'Smithy'

inputs:
  directory:
    description: 'Path (relative to repo root) to the Terraform/OpenTofu recipe'
    required: true
  recipe-nickname:
    description: 'Nickname for this recipe that you set on the platform'
    required: true
  host:
    description: 'Base URL of the platform host (used as OIDC audience and upload target)'
    required: false
    default: 'https://infra-app-916613094271.europe-west1.run.app'
  gcp-credentials-json:
    description: 'GCP service account JSON credentials for authenticating with Google Cloud Provider'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'

permissions:
  id-token: write
  contents: read

branding:
  icon: 'box'
  color: 'blue'
